version: "3"
services:
  web:
    image: "phuicmt/weekends-knowledge-sharing"
    ports:
      - "80:3000"
    expose:
      - "80"
    networks:
      - knowledge-sharing

  portainer_agent:
    image: portainer/agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    networks:
      - knowledge-sharing

  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - knowledge-sharing

volumes:
  portainer_data:

networks:
  knowledge-sharing:
    external: true
